export type DailyBoxOfficeList<T extends string> = {
  audiAcc: T,
  audiChange: T,
  audiCnt:T,
  audiInten:T,
  movieCd:T,
  movieNm:T,
  openDt:T,
  rank:T,
  rankInten:T,
  rankOldAndNew:T,
  rnum:T,
  salesAcc:T,
  salesAmt:T,
  salesChange:T,
  salesInten:T,
  salesShare:T,
  scrnCnt:T,
  showCnt:T,
};